server:
  port: 8083

spring:
  application:
    name: rabbit-queue
  rabbitmq:
    host: "localhost"
    port: "5672"
    username: "guest"
    password: "guest"

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

notifications:
  queue:
    name: "notificationsQueue"
