server:
  port: 8082

spring:
  application:
    name: notification
  datasource: 
    username: 'fdherrera'
    password: 'password'
    url: jdbc:postgresql://localhost:5432/notification
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format-sql: 'true'
    hibernate:
      ddl-auto: create-drop 
    show-sql: 'true'
    generate-ddl: 'true'

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
