server:
  port: 8081
spring:
  application: 
    name: fraud
  datasource: 
    username: 'fdherrera'
    password: 'password'
    url: jdbc:postgresql://localhost:5432/fraud
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format-sql: 'true'
    hibernate:
      ddl-auto: update
    show-sql: 'true'
    generate-ddl: 'true'

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
